### ISSUE TITLE
ArgParser.usage does not print/list out the available commands

### ISSUE THREAD

**Issue by masterashu** [dart-lang/args#134]
When using commands in ArgParser, `usage`  does not print the usage of available commands.
for example
```dart
main(List<String> args){
  var argsParser = ArgParser();
  argsParser.addFlag('flag1', help: 'Help for flag1');
  var argsParser2 = ArgParser();
  argsParser2.addFlag('flag2', help: 'Help for flag2');
  argsParser2.addOption('name', abbr: 'n', help: 'Help for option name');
  argsParser.addCommand('cmd', argsParser2);
  print(argsParser.usage);
}
```
When run the output comes as following:
> --[no-]flag1    Help for flag1  

I believe it would be better to have a description for a command such as
> --[no-]flag1    Help for flag1  
> cmd                Really helpful description for cmd

**Comment by jakemac53** [comment]
See the `CommandRunner` and `Command` classes from the `package:args/command_runner.dart` entrypoint.

Using those will give you the output you are looking for.

I believe that changing the output of the parser itself would likely break the output of those classes (as they use the underlying `usage` property of their nested arg parsers).

**Comment by jakemac53** [comment]
See the `CommandRunner` and `Command` classes from the `package:args/command_runner.dart` entrypoint.

Using those will give you the output you are looking for.

I believe that changing the output of the parser itself would likely break the output of those classes (as they use the underlying `usage` property of their nested arg parsers).
