### ISSUE TITLE
Nullsafe version on pub

### ISSUE THREAD

**Issue by renggli** [dart-lang/args#153]
Please publish the `null_safety` branch on pub.

**Comment by renggli** [comment]
Related: The `null_safety` branch has an upper SDK constraint of `<2.9.0`, which makes it impossible to use on Dart 2.10.

**Comment by munificent** [comment]
I don't believe we're planning to publish any null-safe versions of packages until beta ships, but that should be "soon".

**Comment by pennzht** [comment]
Can we publish the null-safe version on pub now?

**Comment by mannprerak2** [comment]
@munificent any timeline for when a null safe package will be published?

**Comment by munificent** [comment]
It is already null safe on master (thanks, @natebosch). I'm working on getting it rolled into the various places where we use args and make sure it doesn't break things. Once that's complete, I'll publish it.

**Comment by mark-apn** [comment]
Is it possible to do a prerelease? That way anyone can specify 

```yaml
  args: ^2.0.0-nullsafety
```
and the the version from pub.dev. No change of breaking any existing implemented libs.

Thats how all my dependencies are imported now, but only args is via git now. But I get a warning from `args` in my library.

`warning: Publishable packages can't have git dependencies. (invalid_dependency at [dartmd] pubspec.yaml:10)`

![image](https://user-images.githubusercontent.com/62654433/101259955-a61ded80-372c-11eb-8eb5-0cf52c3d0d5e.png)

**Comment by nex3** [comment]
Is there going to be a release of `analyzer` that supports `args` 2.0.0 in unsound mode? Otherwise, I believe there's no way for packages to use null-safe versions of both `args` and `test`.

**Comment by natebosch** [comment]
Yes, we will be working on expanding constraints for these core packages as we go.

**Comment by nex3** [comment]
Is there a timeline for that? I'd like to be able to give Dart users of Dart Sass an idea of when we'll release a null-safe version.

**Comment by nex3** [comment]
Ping!

**Comment by natebosch** [comment]
I'll likely be able to publish sometime in January. There are a few pending PRs that need to get in first and the next couple weeks are tougher to coordinate reviews. If I'm able I'll publish before then, but I'm not sure if that will happen.

**Comment by nex3** [comment]
To be clear, when you say "publish" do you mean "publish a new version of args" or "publish a version of analyzer with wider version constraints"?

**Comment by natebosch** [comment]
I mean publish `args`. The widened constraint will hopefully happen soon after that. @scheglov might have an idea of how quickly we could do that. I don't imagine it should be blocked since the breaking changes don't impact analyzer and this wouldn't require a migration for analyzer.

**Comment by scheglov** [comment]
Do you want `analyzer` to use `  args: '>=1.0.0 < 3.0.0'`?
Where can I find the version of `args 2.0.0` to check that `analyzer` works correctly with it?

**Comment by natebosch** [comment]
> Do you want `analyzer` to use ` args: '>=1.0.0 < 3.0.0'`?

Yes.

> Where can I find the version of args 2.0.0 to check that analyzer works correctly with it?

It doesn't quite exist yet, although the remaining changes that need review before they can be pulled in shouldn't impact anything in the analyzer.
https://github.com/dart-lang/args/pull/170
https://github.com/dart-lang/args/pull/172

Once I have those reviewed I'll pull them into the SDK which should surface any problems with the analyzer.

**Comment by scheglov** [comment]
Oh, I see that we already have `args 2.0.0-nullsafety.0` in the SDK repository.
Once it is ready, ping me, I can publish `analyzer 0.41.2` based on `0.41.1` with `args` version range expanded.
It should not take much time for me.

**Comment by munificent** [comment]
Sorry, I was the hold up here. I've reviewed those two PRs. I'm not sure about #170, but I'll be available to make sure @natebosch and I reach agreement soon.

**Comment by natebosch** [comment]
This is published. It's a little hard to pick up right now because `test` and `analyzer` don't support it yet.

@scheglov - if it's possible, a publish of `analyzer` which supports this and the null safe `crypto` would be helpful before the analyzer migration to reduce the need for overrides.

**Comment by scheglov** [comment]
We planned to keep a branch to publish hot fixes of `0.41.x` that supports SDK `2.7` (more specifically before `2.12`). But if we start depending in `0.41.x` on null safe packages, we effectively will not allow using it on SDK `2.7`.

I guess we could have another branch - `0.42.x`, but then I'm not sure how useful or long lived it would be. We have [this CL](https://dart-review.googlesource.com/c/sdk/+/176486) to migrate `analyzer`. We cannot land it yet, because it requires null-safe `package_config`, and required `pub` to switch to this new `package_config`. If these two can be done soon, we could publish null safe `analyzer` soon.

**Comment by mannprerak2** [comment]
@scheglov [package_config](https://pub.dev/packages/package_config/versions/2.0.0-dev/changelog) has a null safe pre-release now.

**Comment by scheglov** [comment]
OK, thank you, good to know.
Unfortunately Dart SDK still uses the version for `2.7` language version, not the null safe version.
This new version should be pulled into Dart SDK repo before we can land `analyzer` changes.
