### ISSUE TITLE
Exclamation mark in command line option ignored

### ISSUE THREAD

**Issue by benjaminSchilling33** [dart-lang/args#155]
I have CLI application that takes string arguments.

When the strings contain `!` the `!` characters do not appear in the corresponding result.

When the example code is executed like `dart ./bin/cli.dart test -o 'Test!Test'` the print returns `cli test -o TestTest`.

In my opinion this is somehow strange.
Is this defined behaviour? 

Development Environment: Windows 10, did not had time to test using Linux yet

Example code:

```
import 'package:args/command_runner.dart';


void main(List<String> args) async {

  var runner = CommandRunner(
      'dart.exe .\cli.dart', 'test');

  runner
    ..addCommand(TestCommand())
    ..run(args).catchError((error) {
      if (error is! UsageException) throw error;
      print(runner.usage);
    });
}

class TestCommand extends Command {
  final name = "test";
  final description = "test";

  TestCommand() {
    argParser
      ..addOption(
        'option',
        abbr: 'o',
      );

  }

  void run() async {
    print("cli test -o ${argResults['option']}");
  }
}
```

**Comment by jakemac53** [comment]
If you add `print(args);` to the top of your `main` function what do you see?

**Comment by natebosch** [comment]
I think this is a windows thing.

https://stackoverflow.com/questions/3288552/how-can-i-escape-an-exclamation-mark-in-cmd-scripts

**Comment by benjaminSchilling33** [comment]
When I print args as the first thing in main, I get the same.

But when I compile to native using dart2native it works.

Seems to be an issue of the Dart VM.
