### ISSUE TITLE
Allow making options required

### ISSUE THREAD

**Issue by AndiDog** [dart-lang/args#156]
Python's argparse module supports [required=True](https://docs.python.org/3/library/argparse.html#required) to make `-a/--a-long-option` required. This is incredibly helpful if the CLI takes many arguments, which you of course don't want to treat as positional arguments (and require the user to know their order), where some are mandatory.

Admittedly, still calling it "option" is somewhat funky... but it's still a very valid use case.

Suggestion: `addOption('my-long-opt', required: true)`, and `required: true` and `defaultsTo != null` mutually exclusive.

Without this feature, every required argument must be checked with `if (!argResults.wasParsed('my-long-opt')) throw ...`.

**Comment by PoloLacoste** [comment]
Working on it !

I will use `mandatory` instead of `required` because [`required`](https://api.flutter.dev/flutter/meta/required-constant.html) is a top level constant in Dart.

**Comment by PoloLacoste** [comment]
#177
