### ISSUE TITLE
Alias names for arguments

### ISSUE THREAD

**Issue by Hixie** [dart-lang/args#181]
It would be really useful if you could specify aliases for argument names. For example, if someone were to create an application with a "--referer" option, it would be nice to be able to rename it to "--referrer" without breaking backwards compatibility with old scripts that use the old name; allowing them to specify an alias would mean that we could use the correct spelling in all the help docs while supporting both the new name and the old name.

**Comment by jakemac53** [comment]
Would we want to support alias abbreviations as well as full names?

**Comment by Hixie** [comment]
For my use case I don't need that, but I have no objection in principle.

**Comment by Hixie** [comment]
(My use case is renaming a bunch of arguments to the `flutter` tool which I discovered were problematic when doing a recent clenup.)

**Comment by jakemac53** [comment]
Note that `ArgParser` exposes a `final Map<String, Option> options;` public field. The obvious way to implement this is to add extra entries to that for each alias, but that could be breaking if we now have duplicate options in that map, depending on how consumers are using the map.

We could just not expose it that way, but it would likely be useful.

**Comment by Hixie** [comment]
I don't suppose in the meantime I can hack this by manually adding entries to that map, can I?

**Comment by jakemac53** [comment]
It is an unmodifiable map view around the real map, so no unfortunately haha.

**Comment by jakemac53** [comment]
This sounds to me in general like a reasonable and useful feature, so I do think its something we can do. But as always it isn't _quite_ as easy as it sounds on the surface haha. I think really though we just need to answer the question of whether all the aliases should be added to that _public_ options map or not.

**Comment by jakemac53** [comment]
@natebosch are you aware of any _implementations_ of `ArgParser` out there? I didn't even consider that but then I noticed this package has one (`AllowAnythingParser`), so I wonder if there might be others...

**Comment by jakemac53** [comment]
Actually I just checked my local pub copy and internal code and didn't find any implementations so we should be good to add new parameters to methods.

**Comment by munificent** [comment]
Aliases sound like a reasonable feature to me.

>  I think really though we just need to answer the question of whether all the aliases should be added to that public options map or not.

If it were, I wouldn't. Aliases exist to be more permissive in what *input* is allowed. Once the ArgParser has consumed the input, it should be normalized to something simple and consistent for the rest of code to consume. For example, we don't put options in that map for their abbreviations.

**Comment by natebosch** [comment]
> @natebosch are you aware of any _implementations_ of `ArgParser` out there? I didn't even consider that but then I noticed this package has one (`AllowAnythingParser`), so I wonder if there might be others...

I would be fine adding a note in the doc that no class should extend or implement `ArgParser`. I would not expect it's being done today.

**Comment by Hixie** [comment]
I'm totally fine with aliases being entirely opaque to the API. My use case is just supporting legacy deprecated options that I don't even want to document (since they have preferred names).

**Comment by jakemac53** [comment]
I would propose then based on the discussion here adding a `Iterable<String> nameAliases` named argument to the addOption/addMultiOption/addFlag methods, and ensuring that the public `options` getter is _not_ changed (does not contain keys for the aliases).

This allows us to in the future add an additional `Iterable<String> abbrAliases` option if desired, but we probably don't need it initially.

**Comment by munificent** [comment]
How about just `aliases` and we can still do `abbrAliases` in the future if needed. The main name parameter is positional not named so there's already a precedent for `<no name>`/`abbr` and this would just use that as a prefix.

**Comment by jakemac53** [comment]
I would be fine with just `aliases` as well, no real strong opinion either way.
