### ISSUE TITLE
Not-found command should hint about similar ones

### ISSUE THREAD

**Issue by asashour** [dart-lang/args#201]
As was mentioned in https://github.com/flutter/flutter/issues/74521

Shouldn't unknown commands handled like for e.g. `git`:

```
$ git alone
git: 'alone' is not a git command. See 'git --help'.

The most similar command is
        clone
```

**Comment by jakemac53** [comment]
Ya, I have wanted this feature in args for a while 👍 . Some investigation is needed into which algorithm we should use, I know there are a few common ones for edit distance, but I don't have any domain expertise myself.

**Comment by asashour** [comment]
I guess it doesn't really matter as a beginning, we can use [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) or [Dice coefficient](https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient), or even anything simpler.

**Comment by jakemac53** [comment]
Ya its true that even a simple algorithm would likely help out a lot, supporting transposition intuitively seems like a nice improvement to me as well.

**Comment by jakemac53** [comment]
We could even support transposition but only support suggestions with an edit distance of 1. That would be very efficient and easy to implement 🤷‍♂️ .
