### ISSUE TITLE
expose interface for completion

### ISSUE THREAD

**Issue by huang12zheng** [dart-lang/args#212]
ref #17 
* it use argParser.parse(args).
```dart
ArgResults parse(Iterable<String> args) {
    try {
      return argParser.parse(args);
    } on ArgParserException catch (error) {
      if (error.commands.isEmpty) usageException(error.message);

      var command = commands[error.commands.first]!;
      for (var commandName in error.commands.skip(1)) {
        command = command.subcommands[commandName]!;
      }

      command.usageException(error.message);
    }
  }

```
https://github.com/dart-lang/args/blob/master/lib/command_runner.dart#:~:text=be%20called%20externally.-,ArgResults%20parse(Iterable%3CString%3E%20args)%20%7B,%7D,-///%20Runs%20the%20command

---
* info from completion
https://pub.dev/packages/completion
```dart
final argResults = completion.tryArgsCompletion(args, argParser);
```

It might need to expose interface for argsParse.

**Comment by jakemac53** [comment]
I am not quite understanding what you are asking for here, is the `completion` package broken or unable to do some types of completion due to a change in this package?

**Comment by huang12zheng** [comment]
I'm very sorry for asking such a stupid question. Although it may be an issue.
With the following code, CommandRun couldn't add a middle for argResults.
```dart
// [CommandRunner.run]
Future<T?> run(Iterable<String> args) =>
      Future.sync(() => runCommand(parse(args)));
```
* But, I cloud override CommandRun.

```dart
import 'package:args/command_runner.dart';
import 'package:completion/completion.dart';
class TestA<T> extends CommandRunner<T> {
  TestA(String executableName, String description)
      : super(executableName, description);
  Future<T?> run(Iterable<String> args) =>
      // Future.sync(() => runCommand(parse(args)));
      Future.sync(() => runCommand(tryArgsCompletion(args.toList(), argParser)));
}
```
It is my carelessness.
Probably because CommandRunner was so good as encapsulation, just run and glue everything together.

Close it for solving.
