### ISSUE TITLE
Add a CommandRunner example

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/args#219]
Since the `CommandRunner` API works by extending the `Command` class, it's not obvious from the API documentation how to use it (ie which methods are required/recommended to override). An example would be really helpful.

**Comment by devoncarew** [comment]
Do you mean in the `example/` directory or in the readme? There are docs in the readme - https://github.com/dart-lang/args#dispatching-commands - though they could be called out as more specific to CommandRunner. the `example/` code does just demonstrate the single command use, not commandrunner.

**Comment by liamappelbe** [comment]
Yeah, I mean in the `example/` directory. I think it would be helpful to have a more complete example than what's in the readme. I can put something together when I have time.
