### ISSUE TITLE
parser.usage does not show any information about commands.

### ISSUE THREAD

**Issue by gmosx** [dart-lang/args#4]
That's a rather strange omission IMO.

**Comment by nex3** [comment]
The commands associated with an `ArgParser` are pretty bare-bones: they don't have any documentation associated with them, so there wouldn't be anything useful to show in the usage. Leaving them out entirely means that the caller has the freedom to include fuller command documentation without duplicating information.

If you want more in-depth support for command dispatching that includes usage information, check out [`CommandRunner`](http://www.dartdocs.org/documentation/args/0.12.2+4/index.html#args/args-command_runner.CommandRunner).

**Comment by gmosx** [comment]
Hmm, I missed CommandRunner. Is there an example that demonstrates CR's ..usage? (no pun intended).

**Comment by seaneagan** [comment]
You might also be interested in [unscripted](http://pub.dartlang.org/packages/unscripted).

**Comment by gmosx** [comment]
Thanks, I will have a look at unscripted. Still, an example for CommandRunner would be great.

**Comment by nex3** [comment]
There are a number of code examples in [the README](https://github.com/dart-lang/args#dispatching-commands).
