### ISSUE TITLE
Accepting multiple arguments from the find command?

### ISSUE THREAD

**Issue by spierce7** [dart-lang/args#51]
I can't seem to find a way to accept a list of files generated from a find command. Would I have to parse these myself from the `parsedArgs.rest` list, or is there a supported way of doing this?

**Comment by nex3** [comment]
Do you mean something like ``` mycommand `find -name "*.dart"` ```? Yes, you'd use `.rest` to access those.

**Comment by spierce7** [comment]
@nex3 What if I wanted them to be associated with a specific option?

**Comment by munificent** [comment]
You can use `allowMultiple` when defining an option:

```dart
var parser = new ArgParser();
parser.addOption('mode', allowMultiple: true);
```

This lets you pass things like:

```
--mode debug --mode profile
--mode debug,profile
--mode=debug,profile
```

**Comment by spierce7** [comment]
@munificent right, but I haven't found a way for that to work with the find command returning multiple files very well.

**Comment by nex3** [comment]
You can use the `paste` command to comma-separate the files: ``` mycommand `find -name "*.dart" | paste -s -d "," -` ```, or you can use `-printf` to pass each file separately to the flag: ``` mycommand `find -name "*.dart" -printf "--flag %p\n"` ```.
