### ISSUE TITLE
Don't throw an Error when calling `wasParsed()` for a non-supplied option.

### ISSUE THREAD

**Issue by KOGI** [dart-lang/args#62]
The [documentation for `wasParsed()`](https://github.com/dart-lang/args/blob/master/lib/src/arg_results.dart#L81) says that the method will return `true|false` depending on whether or not the option was parsed. However, in the case where the option was NOT parsed, an `ArgumentError` is thrown rather than returning `false`.

This duplicates the functionality of the `[]` operator on the same class, which is not only redundant, but makes testing for the existence of options more difficult. Consider the following if the `bar` option is not given:

```dart
var parser = new ArgParser();
parser.addCommand("foo")
  ..addOption('bar',
      abbr: 'b',
      help: 'the bar you love most (optional)');

ArgResults cliArgs = parser.parse(arguments);

if (cliArgs.command.name == 'foo') {
  if (cliArgs.command.wasParsed('bar')) { // -- bar arg was given
    // do something with bar

  } else { // -- no bar arg :(
    // do something else // -- this will never happen due to the thrown error
  }
}
```

The ONLY option here is to use a try/catch (most likely with an empty catch block) to test for the existence of options.

**Comment by nex3** [comment]
It only throws if the option wasn't *defined* on the arg parser. If it was defined and not passed, it returns `false`.

**Comment by KOGI** [comment]
Ah, you're totally right! I had an error in my code that I didn't realize was there.

It would be nice to have a similar helper, though, that would allow something like `command.hasOption(name)` to check if the option was defined for a given command or not.
