### ISSUE TITLE
Please bump version to 1.0 when stable

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/args#65]
Pre-1.0 version numbers make it look like the package is not yet ready for use.

**Comment by nex3** [comment]
I believe @munificent had some breaking changes he's been planning for this package—switching the default value of `allowMultiple`, for example.

**Comment by munificent** [comment]
> he's been planning for this package

Oh, man, I haven't thought about args in ages. :(

I don't think I'll be getting to it any time soon.

**Comment by nex3** [comment]
Do you remember what breaking changes you were planning to make? I can handle the actual upgrade.

**Comment by munificent** [comment]
I don't. Your comment about `allowMultiple` is the only thing even faintly familiar.
