### ISSUE TITLE
No easy way to toggle allowTrailingOptions on subcommands

### ISSUE THREAD

**Issue by Hixie** [dart-lang/args#69]
I want a subcommand that has a different value for allowTrailingOptions than the default, but there's nowhere for me to override the creation of the ArgParser that ends up in _argParser in Command.

**Comment by nex3** [comment]
You can override `Command.argParser`—the rest of the `Command` API uses that getter.

**Comment by Hixie** [comment]
That still creates the redundant ArgParser though, no? That seems suboptimal...

It would be nice if this was documented as the correct and supported way to do this, because when I looked at the code it was not obvious that this was a safe thing to do.

**Comment by nex3** [comment]
> That still creates the redundant ArgParser though, no? That seems suboptimal...

I doubt anything about the args package is optimal in terms of performance... it's not something we really expect to be used heavily in performance hotspots.

> It would be nice if this was documented as the correct and supported way to do this, because when I looked at the code it was not obvious that this was a safe thing to do.

I'll see if I can tweak the docs to make this clearer.
