### ISSUE TITLE
Documentation requests (e.g. addOption(valueHelp))

### ISSUE THREAD

**Issue by Hixie** [dart-lang/args#73]
https://www.dartdocs.org/documentation/args/1.0.0/args/ArgParser/addOption.html doesn't define most of its arguments, for example valueHelp.
I guessed that addOption creates an Option under the hood but unfortunately the docs for Option (https://www.dartdocs.org/documentation/args/1.0.0/args/Option-class.html) also don't define the similarly named properties, including valueHelp.

**Comment by srawlins** [comment]
I'm also curious why the argument of `callback` isn't typed. Isn't it always a String?
