### ISSUE TITLE
FR: support +/- for multiple options

### ISSUE THREAD

**Issue by har79** [dart-lang/args#91]
For example, with an option like:

```
> bakifier --cakes=carrot,chocolate,red-velvet
Baked carrot, chocolate, and red-velvet cakes. Yum!
```

support +value and -value to modify the default:

```
> bakifier --cakes=+courgette
Baked chocolate, vanilla, and courgette cakes. Yum!
```

**Comment by nex3** [comment]
This is a lot of parsing complexity that, as far as I know, isn't a standard argument-parsing format. We try to keep this package pretty lean and close to the conventions used by most command-line programs, and I think this is too far afield.
